name: $(Date:yyyyMMdd)$(Rev:rr)

parameters:
  - name: displayVersion
    displayName: Enter the display version
    type: string
    default: '2.3.2'

variables:
  - group: 'App Configuration'
  - name: displayVersion
    value: ${{ parameters.displayVersion }}

trigger: none

stages:
  # Stage for MAUI iOS
- stage: build_maui_ios
  jobs:
  - job: build_maui_ios_app
    displayName: Build App for iOS
    pool:
      vmImage: macos-latest
    
    steps:

    # build project
    - task: CmdLine@2
      displayName: 'Show Version and Build Number'
      inputs:
       script: |
        echo Build info
        echo target framework $(app-target-framework-ios)
        echo target build number $(Build.BuildNumber)
        echo displayVersion $(displayVersion)
    
    - task: InstallAppleCertificate@2
      inputs:
        certSecureFile: '$(apple-certificate-name)'
        certPwd: '$(apple-certificate-password)'
        keychain: 'temp'
    
    - task: InstallAppleProvisioningProfile@1
      inputs:
        provisioningProfileLocation: 'secureFiles'
        provProfileSecureFile: '$(apple-provisioning-profile-name)'
    
    # Install .NET SDKs  
    - task: UseDotNet@2
      displayName: Install .NET SDK
      inputs:
        packageType: 'sdk'
        version: '$(dotnet-version)'
        includePreviewVersions: false
    
     # Install all workloads your solution is supported
    - powershell: dotnet workload install maui-android maui-ios
      displayName: Install .NET MAUI Workload
    
     # build project
    - task: CmdLine@2
      displayName: 'Build project'
      inputs:
       script: |
        dotnet publish $(app-path-project) -f $(app-target-framework-ios) -c Release /p:ApplicationId=/p:ApplicationDisplayVersion=${{ parameters.displayVersion }} /p:ApplicationVersion=$(Build.BuildNumber) /p:ArchiveOnBuild=true /p:EnableAssemblyILStripping=false /p:RuntimeIdentifier=ios-arm64
   
    - task: CopyFiles@2
      displayName: 'Copy files to: $(Build.ArtifactStagingDirectory)'
      inputs:
        SourceFolder: '$(Agent.BuildDirectory)'
        Contents: '**/*.ipa'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        CleanTargetFolder: true
        flattenFolders: true
      
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifacts'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop_maui_ios'
        publishLocation: 'Container'

    - task: AppCenterDistribute@3
      inputs:
        serverEndpoint: 'AppCenter Connection'
        appSlug: '$(app-slug-ios)'
        appFile: '$(app-file-ios)'
        releaseNotesOption: 'file'
        releaseNotesFile: '$(app-path-root)/releasenotes.txt'
        destinationType: 'groups' 
